import type { SentryCliCommitsOptions, SentryCliNewDeployOptions, SentryCliOptions, SentryCliUploadSourceMapsOptions } from '@sentry/cli'

/** options */
export interface Options extends SentryCliOptions {
  /**
   * The URL of the Sentry
   */
  url: string
  /**
   * Orgination name in Sentry
   */
  org: string
  /**
   * Project name in Senrty
   */
  project: string
  /**
   * Auth token
   */
  authToken: string
  /**
   * Release version,
   * auto generated by git commit hash,
   * you can also config it by yourself
   */
  release?: string
  /**
   * If use short commit hash for release version
   * @default true
   */
  shortRelease?: boolean
  /**
   * Sourcemap configs
   */
  sourcemap?: SourcemapOptions
  /**
   * Deploy configs
   */
  deploy?: DeployOptions
  /**
   * If delete local sourcemap after uploaded,
   * @default true
   */
  clean?: boolean
  /**
   * If delete remote previous sourcemap in Sentry under the same `release`
   * @default true
   */
  delete?: boolean
  /**
   * If finalize a release after uploaded
   * @default true
   */
  finalize?: boolean
  /**
   * Path of config file
   */
  configFile?: string
  /**
   * Commits configs
   */
  commits?: SentryCliCommitsOptions
}

export interface SourcemapOptions extends Omit<SentryCliUploadSourceMapsOptions, 'include'> {
  /**
   * Sourcemap paths
   * @default [`./${vite.build.outDir}/${vite.build.assetsDir}`]
   */
  include?: SentryCliUploadSourceMapsOptions['include']
  /**
   * !IMPORTANT!: MUST START WITH `~/`
   * @default `~${vite.env.BASE_URL}assets/`
   */
  urlPrefix?: SentryCliUploadSourceMapsOptions['urlPrefix']
}

export interface DeployOptions extends Omit<SentryCliNewDeployOptions, 'env'> {
  /**
   * Environment
   * @default `vite.mode`
   */
  env?: SentryCliNewDeployOptions['env']
}
